BSM_Disrupt_Prototype/BSM_Disrupt_Prototype/Pages/BSM_Workshop/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using BSM_Disrupt_Prototype.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BSM_Disrupt_Prototype.Pages.BSM_Workshop
{
	public class CreateModel : PageModel
    {

        private AppDbContext _db;

        [BindProperty]
        public Products Prod { get; set; }

        public CreateModel(AppDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid) { return Page(); }
            Prod.Active = true;
            foreach (var file in Request.Form.Files)
            {
                MemoryStream ms = new MemoryStream();
                file.CopyTo(ms);
                Prod.ImageData = ms.ToArray();

                ms.Close();
                ms.Dispose();
            }

            _db.Products.Add(Prod);
            await _db.SaveChangesAsync();
            return RedirectToPage("/BSM_Workshop/Create");
        }

        public void OnGet()
        {
        }
    }
}

BSM_Disrupt_Prototype/BSM_Disrupt_Prototype/Pages/BSM_Workshop/CreateProducts.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using BSM_Disrupt_Prototype.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BSM_Disrupt_Prototype.Pages.BSM_Workshop
{
	public class CreateProductsModel : PageModel
    {

        private AppDbContext _db;

        [BindProperty]
        public Products Prod { get; set; }

        public CreateProductsModel(AppDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid) { return Page(); }
            Prod.Active = true;
            foreach (var file in Request.Form.Files)
            {
                MemoryStream ms = new MemoryStream();
                file.CopyTo(ms);
                Prod.ImageData = ms.ToArray();

                ms.Close();
                ms.Dispose();
            }

            _db.Products.Add(Prod);
            await _db.SaveChangesAsync();
            return RedirectToPage("/BSM_Workshop/CreateProducts");
        }

        public void OnGet()
        {
        }
    }
}

BSM_Disrupt_Prototype/BSM_Disrupt_Prototype/Pages/BSM_Workshop/EditProducts.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using BSM_Disrupt_Prototype.Data;
using Microsoft.EntityFrameworkCore;

namespace BSM_Disrupt_Prototype.Pages.BSM_Workshop
{
	public class EditProductsModel : PageModel
    {
        [BindProperty]
        public Products Item { get; set; }

        private readonly AppDbContext _db;
        public EditProductsModel(AppDbContext db) { _db = db; }

        public async Task<IActionResult> OnGetAsync(int id)
        {
            Item = await _db.Products.FindAsync(id);
            if (Item == null)
            {
                return RedirectToPage("/Index");
            }
            return Page();
        }

        public async Task<IActionResult> OnPostSaveAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _db.Attach(Item).State = EntityState.Modified;
            try
            {
                await _db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException e)
            {
                throw new Exception($"Item {Item.ID} not found!", e);
            }
            return RedirectToPage("/Index");
        }


    }
}

BSM_Disrupt_Prototype/BSM_Disrupt_Prototype/Pages/BSM_Workshop/ManageProducts.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using BSM_Disrupt_Prototype.Data;
using System.IO;
using Microsoft.EntityFrameworkCore;
using System.Globalization;

namespace BSM_Disrupt_Prototype.Pages.BSM_Workshop
{
	public class ManageProductsModel : PageModel
    {

        public NumberFormatInfo myNumberFormatInfo = new CultureInfo("ms-BN", false).NumberFormat; // Currency Format for Brunei Dollar.

        private readonly AppDbContext _db;
        public ManageProductsModel(AppDbContext db)
        {
            _db = db;
        }
        public IList<Products> Products { get; private set; }

        [BindProperty]
        public string Search { get; set; }

        public void OnGet()
        {
            Products = _db.Products.FromSqlRaw("SELECT * FROM Products").ToList();
        }

        public IActionResult OnPostSearch()
        {
            Products = _db.Products
                .FromSqlRaw("SELECT * FROM Products WHERE Name LIKE '" + Search + "%'")
                .ToList();
            return Page();
        }

        public async Task<IActionResult> OnPostDeleteAsync(int itemID)
        {
            var item = await _db.Products.FindAsync(itemID);
            item.Active = false; //set item as deleted
            _db.Attach(item).State = EntityState.Modified;
            try
            {
                await _db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException e)
            {
                throw new Exception($"Item {item.ID} not found!", e);
            }
            return RedirectToPage();
        }



    }
}

BSM_Disrupt_Prototype/BSM_Disrupt_Prototype/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BSM_Disrupt_Prototype.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

BSM_Disrupt_Prototype/BSM_Disrupt_Prototype/Pages/Products.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using BSM_Disrupt_Prototype.Data;
using Microsoft.EntityFrameworkCore;
using System.Globalization;

namespace BSM_Disrupt_Prototype.Pages
{
	public class ProductsModel : PageModel
    {

        public NumberFormatInfo myNumberFormatInfo = new CultureInfo("ms-BN", false).NumberFormat; // Currency Format for Brunei Dollar.

        private readonly AppDbContext _db;
        public ProductsModel(AppDbContext db)
        {
            _db = db;
        }
        public IList<Products> Products { get; private set; }

        [BindProperty]
        public string Search { get; set; }

        public void OnGet()
        {
            Products = _db.Products.FromSqlRaw("SELECT * FROM Products WHERE Active = 1").ToList();
        }

        public IActionResult OnPostSearch()
        {
            Products = _db.Products
                .FromSqlRaw("SELECT * FROM Products WHERE Active = 1 AND Name LIKE '" + Search + "%'")
                .ToList();
            return Page();
        }

    }
}

BSM_Disrupt_Prototype/BSM_Disrupt_Prototype/Pages/BSM_Workshop/Create.cshtml
@page
@model BSM_Disrupt_Prototype.Pages.BSM_Workshop.CreateModel
@{
    ViewData["Title"] = "Create";
    Layout = "~/Pages/_Layout.cshtml";
}

<h1>Create - Add BSM Products</h1>
<p> Enter details of the product:</p>

<form method="post" enctype="multipart/form-data">
    <div>Name:  <input asp-for="Prod.Name" /></div>
    <div>Price:  <input asp-for="Prod.Price" /></div>
    <div>Description:  <input asp-for="Prod.Description" /></div>
    <div>Image Description <input asp-for="Prod.Description" /></div>
    <div>
        Upload Image:<br />
        <input type="file" id="file1"
               name="file1"
               multiple="multiple" />
    </div>
    <input type="submit" />
</form>

BSM_Disrupt_Prototype/BSM_Disrupt_Prototype/Pages/BSM_Workshop/CreateProducts.cshtml
@page
@model BSM_Disrupt_Prototype.Pages.BSM_Workshop.CreateProductsModel
@{
    ViewData["Title"] = "CreateProducts";
    Layout = "~/Pages/_Layout.cshtml";
}

<h1>Create - Add BSM Products</h1>
<p> Enter details of the product:</p>

<form method="post" enctype="multipart/form-data">
    <div asp-validation-summary="All"></div>”
    <div>Name:  <input asp-for="Prod.Name" /></div>
    <div>Price:  <input asp-for="Prod.Price" /></div>
    <div>Description:  <input asp-for="Prod.Description" /></div>
    <div>Image Description: <input asp-for="Prod.ImageDescription" /></div>
    <div>Serial Number: <input asp-for="Prod.SerialNumber" /></div>
    <div>
        Upload Image:<br />
        <input type="file" id="file1"
               name="file1"
               multiple="multiple" />
    </div>
    <input type="submit" />
</form>

BSM_Disrupt_Prototype/BSM_Disrupt_Prototype/Pages/BSM_Workshop/EditProducts.cshtml
@page
@model BSM_Disrupt_Prototype.Pages.BSM_Workshop.EditProductsModel
@{
    ViewData["Title"] = "EditProducts";
    Layout = "~/Pages/_Layout.cshtml";
}

<h2>Edit Item - @Model.Item.Name</h2>

<form method="post">
    <div>
        <h3>Item:</h3>
        <div>
            <input asp-for="Item.ID" type="hidden"/>

            <label>Name</label>
            <div><input asp-for="Item.Name"/></div>

            <label>Price</label>
            <div><input asp-for="Item.Price"/></div>

            <label>Description</label>
            <div><input asp-for="Item.Description"/></div>

            <label>Image Description</label>
            <div><input asp-for="Item.ImageDescription"/></div>

            <input asp-for="Item.ImageData" type="hidden"/>

            <label>Serial Number</label>
            <div><input asp-for="Item.SerialNumber"/></div>

            <input asp-for="Item.Active" type="hidden"/>
        </div>
    </div>
    <div>
        <button type="submit" asp-page-handler="Save">Save</button>
    </div>
</form>

BSM_Disrupt_Prototype/BSM_Disrupt_Prototype/Pages/BSM_Workshop/ManageProducts.cshtml
@page
@model BSM_Disrupt_Prototype.Pages.BSM_Workshop.ManageProductsModel
@{
    ViewData["Title"] = "ManageProducts";
    Layout = "~/Pages/_Layout.cshtml";
}

<h1>BSM Workshop Example 1</h1>

<h2>Products</h2>

<h3>Search</h3>
<form method="post">
    <div>Search  <input asp-for="Search" /></div>
    <button type="submit" asp-page-handler="Search">Submit</button>/>
</form>

<form method="post">
    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Price</th>
                <th>Serial Number</th>
                <th>Active</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var prod in Model.Products)
            {
                <tr>
                    <td>@prod.Name</td>
                    <td>@prod.Description</td>
                    <td>@prod.Price.ToString("C", Model.myNumberFormatInfo)</td>
                    <td>@prod.SerialNumber</td>
                    <td>@prod.Active</td>
                    @{
                        try
                        {
                            <td>
                                <img src="@string.Format("data:image/jpg;base64,{0}",
                                     Convert.ToBase64String(prod.ImageData))" alt="@prod.ImageDescription" />
                            </td>
                        }
                        catch
                        {
                            <td>
                                <img src="/IMAGES/empty.png" alt="No Image Provided" />
                            </td>
                        }
                    }
                <td>
                    <a asp-page="/BSM_Workshop/EditProducts" asp-route-id="@prod.ID">edit</a>.
                    <button type="submit" asp-page-handler="Delete" asp-route-itemID="@prod.ID">delete</button>
                </td>
                </tr>
            }
        </tbody>
    </table>
</form>

BSM_Disrupt_Prototype/BSM_Disrupt_Prototype/Pages/Index.cshtml
@page
@model BSM_Disrupt_Prototype.Pages.IndexModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Pages/_Layout.cshtml";

    string test = "I see trees are green."; // Example of what you can do on a razor page.
}

<h1>Index</h1>
<h2>test name: @test</h2>
<img src="~/IMAGES/BSM-Logo-500.png" />

BSM_Disrupt_Prototype/BSM_Disrupt_Prototype/Pages/Products.cshtml
@page
@model BSM_Disrupt_Prototype.Pages.ProductsModel
@{
    ViewData["Title"] = "Products";
    Layout = "~/Pages/_Layout.cshtml";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<h1>BSM Workshop Example 1</h1>

<h2>Products</h2>

<h3>Search</h3>
<form method="post">
    <div>Search  <input asp-for="Search" /></div>
    <button type="submit" asp-page-handler="Search">Submit</button>
</form>

<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var prod in Model.Products)
        {
            <tr>
                <td>@prod.Name</td>
                <td>@prod.Description</td>
                <td>@prod.Price.ToString("C", Model.myNumberFormatInfo)</td>
                @{
                    try
                    {
                        <td>
                            <img src="@string.Format("data:image/jpg;base64,{0}",
                                     Convert.ToBase64String(prod.ImageData))" alt="@prod.ImageDescription" />
                        </td>
                    }
                    catch
                    {
                        <td>
                            <img src="/IMAGES/empty.png" alt="No Image Provided" />
                        </td>
                    }
                }
            </tr>
        }

    </tbody>
</table>

BSM_Disrupt_Prototype/BSM_Disrupt_Prototype/Pages/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/CSS/StyleSheet.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        <a asp-page="/Index">Home</a>
        <a asp-page="/Products">Products</a>
        <a asp-page="/BSM_Workshop/CreateProducts">Create Products</a>
        <a asp-page="/BSM_Workshop/ManageProducts">Manage Products</a>
        @RenderBody()
    </div>
</body>
</html>